### ISSUE TITLE
Feature request: pass this to callback in componentDidMount 

### ISSUE THREAD

**Issue by wuct** [evenchange4/react-lifecycle-hoc#15]
One of the common use cases in `componentDidMount` is doing DOM operations, ex: get the `offsetHeight` of a DOM, bind a listener to a DOM event. We can achieve this by using `findDOMNode(this)` inside `componentDidMount`, so I suggest we pass `this` instead of `this.props` to the callback [here](https://github.com/evenchange4/react-lifecycle-hoc/blob/master/src/componentDidMount.js#L7).

Change from

```
componentDidMount = () => callback(this.props)
```

to

```
componentDidMount = () => callback(this)
```

This will causing a breaking change, however the modification would be easy. Consumers can change from `(props) => {}` to  use object destruction  `({ props }) => {}` inside their callbacks.

**Comment by evenchange4** [comment]
okay, sounds good.
Are you working on this?

吳敬庭 notifications@github.com 於 2016年3月26日 星期六寫道：

> One of the common use cases in componentDidMount is doing DOM operations,
> ex: get the offsetHeight of a DOM, bind a listener to a DOM event. We can
> achieve this by using findDOMNode(this) inside componentDidMount, so I
> suggest we pass this instead of this.props to the callback here
> https://github.com/evenchange4/react-lifecycle-hoc/blob/master/src/componentDidMount.js#L7
> .
> 
> Change from
> 
> componentDidMount = () => callback(this.props)
> 
> to
> 
> componentDidMount = () => callback(this)
> 
> This will causing a breaking change, however the modification would be
> easy. Consumers can change from (props) => {} to use object destruction ({
> props }) => {} inside their callbacks.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/evenchange4/react-lifecycle-hoc/issues/15

##

**Comment by wuct** [comment]
Not yet, but I can create a PR for this today
